package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Balsa generated by hbm2java
 */
@Entity
@Table(name = "balsa", catalog = "fluvialpass")
public class Balsa implements java.io.Serializable {

	private Integer idbalsa;
	private Cidade cidade;
	private String nomeBalsa;
	private Set<Barco> barcos = new HashSet<Barco>(0);

	public Balsa() {
	}

	public Balsa(Cidade cidade) {
		this.cidade = cidade;
	}

	public Balsa(Cidade cidade, String nomeBalsa, Set<Barco> barcos) {
		this.cidade = cidade;
		this.nomeBalsa = nomeBalsa;
		this.barcos = barcos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idbalsa", unique = true, nullable = false)
	public Integer getIdbalsa() {
		return this.idbalsa;
	}

	public void setIdbalsa(Integer idbalsa) {
		this.idbalsa = idbalsa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCidade", nullable = false)
	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	@Column(name = "nomeBalsa", length = 45)
	public String getNomeBalsa() {
		return this.nomeBalsa;
	}

	public void setNomeBalsa(String nomeBalsa) {
		this.nomeBalsa = nomeBalsa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "balsa")
	public Set<Barco> getBarcos() {
		return this.barcos;
	}

	public void setBarcos(Set<Barco> barcos) {
		this.barcos = barcos;
	}

}
