package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cep generated by hbm2java
 */
@Entity
@Table(name = "cep", catalog = "fluvialpass")
public class Cep implements java.io.Serializable {

	private String ncep;
	private Bairro bairro;
	private String nomeRua;
	private Set<Endereco> enderecos = new HashSet<Endereco>(0);

	public Cep() {
	}

	public Cep(String ncep, Bairro bairro) {
		this.ncep = ncep;
		this.bairro = bairro;
	}

	public Cep(String ncep, Bairro bairro, String nomeRua, Set<Endereco> enderecos) {
		this.ncep = ncep;
		this.bairro = bairro;
		this.nomeRua = nomeRua;
		this.enderecos = enderecos;
	}

	@Id

	@Column(name = "nCEP", unique = true, nullable = false, length = 255)
	public String getNcep() {
		return this.ncep;
	}

	public void setNcep(String ncep) {
		this.ncep = ncep;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idBairro", nullable = false)
	public Bairro getBairro() {
		return this.bairro;
	}

	public void setBairro(Bairro bairro) {
		this.bairro = bairro;
	}

	@Column(name = "nomeRua", length = 256)
	public String getNomeRua() {
		return this.nomeRua;
	}

	public void setNomeRua(String nomeRua) {
		this.nomeRua = nomeRua;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cep")
	public Set<Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

}
