package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoginId generated by hbm2java
 */
@Embeddable
public class LoginId implements java.io.Serializable {

	private int idlogin;
	private int usuarioIdUsuario;

	public LoginId() {
	}

	public LoginId(int idlogin, int usuarioIdUsuario) {
		this.idlogin = idlogin;
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "idlogin", nullable = false)
	public int getIdlogin() {
		return this.idlogin;
	}

	public void setIdlogin(int idlogin) {
		this.idlogin = idlogin;
	}

	@Column(name = "usuario_idUsuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginId))
			return false;
		LoginId castOther = (LoginId) other;

		return (this.getIdlogin() == castOther.getIdlogin())
				&& (this.getUsuarioIdUsuario() == castOther.getUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdlogin();
		result = 37 * result + this.getUsuarioIdUsuario();
		return result;
	}

}
