package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefone generated by hbm2java
 */
@Entity
@Table(name = "telefone", catalog = "fluvialpass")
public class Telefone implements java.io.Serializable {

	private TelefoneId id;
	private Barco barco;
	private Usuario usuario;
	private String ntelefone;
	private String ddd;

	public Telefone() {
	}

	public Telefone(TelefoneId id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public Telefone(TelefoneId id, Barco barco, Usuario usuario, String ntelefone, String ddd) {
		this.id = id;
		this.barco = barco;
		this.usuario = usuario;
		this.ntelefone = ntelefone;
		this.ddd = ddd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idTelefone", column = @Column(name = "idTelefone", nullable = false)),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "idUsuario", nullable = false)) })
	public TelefoneId getId() {
		return this.id;
	}

	public void setId(TelefoneId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idBarco")
	public Barco getBarco() {
		return this.barco;
	}

	public void setBarco(Barco barco) {
		this.barco = barco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nTelefone", length = 45)
	public String getNtelefone() {
		return this.ntelefone;
	}

	public void setNtelefone(String ntelefone) {
		this.ntelefone = ntelefone;
	}

	@Column(name = "ddd", length = 45)
	public String getDdd() {
		return this.ddd;
	}

	public void setDdd(String ddd) {
		this.ddd = ddd;
	}

}
