package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TelefoneId generated by hbm2java
 */
@Embeddable
public class TelefoneId implements java.io.Serializable {

	private int idTelefone;
	private int idUsuario;

	public TelefoneId() {
	}

	public TelefoneId(int idTelefone, int idUsuario) {
		this.idTelefone = idTelefone;
		this.idUsuario = idUsuario;
	}

	@Column(name = "idTelefone", nullable = false)
	public int getIdTelefone() {
		return this.idTelefone;
	}

	public void setIdTelefone(int idTelefone) {
		this.idTelefone = idTelefone;
	}

	@Column(name = "idUsuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TelefoneId))
			return false;
		TelefoneId castOther = (TelefoneId) other;

		return (this.getIdTelefone() == castOther.getIdTelefone()) && (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTelefone();
		result = 37 * result + this.getIdUsuario();
		return result;
	}

}
