package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoBarco generated by hbm2java
 */
@Entity
@Table(name = "tipoBarco", catalog = "fluvialpass")
public class TipoBarco implements java.io.Serializable {

	private Integer idTipoBarco;
	private String nomeTipoBarco;
	private Set<Barco> barcos = new HashSet<Barco>(0);

	public TipoBarco() {
	}

	public TipoBarco(String nomeTipoBarco, Set<Barco> barcos) {
		this.nomeTipoBarco = nomeTipoBarco;
		this.barcos = barcos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoBarco", unique = true, nullable = false)
	public Integer getIdTipoBarco() {
		return this.idTipoBarco;
	}

	public void setIdTipoBarco(Integer idTipoBarco) {
		this.idTipoBarco = idTipoBarco;
	}

	@Column(name = "nomeTipoBarco", length = 45)
	public String getNomeTipoBarco() {
		return this.nomeTipoBarco;
	}

	public void setNomeTipoBarco(String nomeTipoBarco) {
		this.nomeTipoBarco = nomeTipoBarco;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoBarco")
	public Set<Barco> getBarcos() {
		return this.barcos;
	}

	public void setBarcos(Set<Barco> barcos) {
		this.barcos = barcos;
	}

}
