package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsuarioWeb generated by hbm2java
 */
@Entity
@Table(name = "usuario_web", catalog = "fluvialpass")
public class UsuarioWeb implements java.io.Serializable {

	private UsuarioWebId id;
	private Usuario usuario;
	private Integer idade;
	private Set<Passagem> passagems = new HashSet<Passagem>(0);

	public UsuarioWeb() {
	}

	public UsuarioWeb(UsuarioWebId id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public UsuarioWeb(UsuarioWebId id, Usuario usuario, Integer idade, Set<Passagem> passagems) {
		this.id = id;
		this.usuario = usuario;
		this.idade = idade;
		this.passagems = passagems;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idusuarioWeb", column = @Column(name = "idusuario_web", nullable = false)),
			@AttributeOverride(name = "usuarioIdUsuario", column = @Column(name = "usuario_idUsuario", nullable = false)) })
	public UsuarioWebId getId() {
		return this.id;
	}

	public void setId(UsuarioWebId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_idUsuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "idade")
	public Integer getIdade() {
		return this.idade;
	}

	public void setIdade(Integer idade) {
		this.idade = idade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioWeb")
	public Set<Passagem> getPassagems() {
		return this.passagems;
	}

	public void setPassagems(Set<Passagem> passagems) {
		this.passagems = passagems;
	}

}
