package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioGuicheId generated by hbm2java
 */
@Embeddable
public class UsuarioGuicheId implements java.io.Serializable {

	private int idusuarioGuiche;
	private int usuarioIdUsuario;

	public UsuarioGuicheId() {
	}

	public UsuarioGuicheId(int idusuarioGuiche, int usuarioIdUsuario) {
		this.idusuarioGuiche = idusuarioGuiche;
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "idusuario_guiche", nullable = false)
	public int getIdusuarioGuiche() {
		return this.idusuarioGuiche;
	}

	public void setIdusuarioGuiche(int idusuarioGuiche) {
		this.idusuarioGuiche = idusuarioGuiche;
	}

	@Column(name = "usuario_idUsuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioGuicheId))
			return false;
		UsuarioGuicheId castOther = (UsuarioGuicheId) other;

		return (this.getIdusuarioGuiche() == castOther.getIdusuarioGuiche())
				&& (this.getUsuarioIdUsuario() == castOther.getUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdusuarioGuiche();
		result = 37 * result + this.getUsuarioIdUsuario();
		return result;
	}

}
