package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioAppId generated by hbm2java
 */
@Embeddable
public class UsuarioAppId implements java.io.Serializable {

	private int idusuarioApp;
	private int usuarioIdUsuario;

	public UsuarioAppId() {
	}

	public UsuarioAppId(int idusuarioApp, int usuarioIdUsuario) {
		this.idusuarioApp = idusuarioApp;
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "idusuario_app", nullable = false)
	public int getIdusuarioApp() {
		return this.idusuarioApp;
	}

	public void setIdusuarioApp(int idusuarioApp) {
		this.idusuarioApp = idusuarioApp;
	}

	@Column(name = "usuario_idUsuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioAppId))
			return false;
		UsuarioAppId castOther = (UsuarioAppId) other;

		return (this.getIdusuarioApp() == castOther.getIdusuarioApp())
				&& (this.getUsuarioIdUsuario() == castOther.getUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdusuarioApp();
		result = 37 * result + this.getUsuarioIdUsuario();
		return result;
	}

}
