package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsuarioApp generated by hbm2java
 */
@Entity
@Table(name = "usuario_app", catalog = "fluvialpass")
public class UsuarioApp implements java.io.Serializable {

	private UsuarioAppId id;
	private Usuario usuario;
	private Set<Passagem> passagems = new HashSet<Passagem>(0);

	public UsuarioApp() {
	}

	public UsuarioApp(UsuarioAppId id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public UsuarioApp(UsuarioAppId id, Usuario usuario, Set<Passagem> passagems) {
		this.id = id;
		this.usuario = usuario;
		this.passagems = passagems;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idusuarioApp", column = @Column(name = "idusuario_app", nullable = false)),
			@AttributeOverride(name = "usuarioIdUsuario", column = @Column(name = "usuario_idUsuario", nullable = false)) })
	public UsuarioAppId getId() {
		return this.id;
	}

	public void setId(UsuarioAppId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_idUsuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioApp")
	public Set<Passagem> getPassagems() {
		return this.passagems;
	}

	public void setPassagems(Set<Passagem> passagems) {
		this.passagems = passagems;
	}

}
