package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioVendedorPassagemId generated by hbm2java
 */
@Embeddable
public class UsuarioVendedorPassagemId implements java.io.Serializable {

	private int idusuarioVendedorPassagem;
	private int usuarioIdUsuario;

	public UsuarioVendedorPassagemId() {
	}

	public UsuarioVendedorPassagemId(int idusuarioVendedorPassagem, int usuarioIdUsuario) {
		this.idusuarioVendedorPassagem = idusuarioVendedorPassagem;
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "idusuario_vendedor_passagem", nullable = false)
	public int getIdusuarioVendedorPassagem() {
		return this.idusuarioVendedorPassagem;
	}

	public void setIdusuarioVendedorPassagem(int idusuarioVendedorPassagem) {
		this.idusuarioVendedorPassagem = idusuarioVendedorPassagem;
	}

	@Column(name = "usuario_idUsuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioVendedorPassagemId))
			return false;
		UsuarioVendedorPassagemId castOther = (UsuarioVendedorPassagemId) other;

		return (this.getIdusuarioVendedorPassagem() == castOther.getIdusuarioVendedorPassagem())
				&& (this.getUsuarioIdUsuario() == castOther.getUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdusuarioVendedorPassagem();
		result = 37 * result + this.getUsuarioIdUsuario();
		return result;
	}

}
