package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioGuiche generated by hbm2java
 */
@Entity
@Table(name = "usuario_guiche", catalog = "fluvialpass")
public class UsuarioGuiche implements java.io.Serializable {

	private UsuarioGuicheId id;
	private Porto porto;
	private Usuario usuario;
	private Integer nguiche;

	public UsuarioGuiche() {
	}

	public UsuarioGuiche(UsuarioGuicheId id, Porto porto, Usuario usuario) {
		this.id = id;
		this.porto = porto;
		this.usuario = usuario;
	}

	public UsuarioGuiche(UsuarioGuicheId id, Porto porto, Usuario usuario, Integer nguiche) {
		this.id = id;
		this.porto = porto;
		this.usuario = usuario;
		this.nguiche = nguiche;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idusuarioGuiche", column = @Column(name = "idusuario_guiche", nullable = false)),
			@AttributeOverride(name = "usuarioIdUsuario", column = @Column(name = "usuario_idUsuario", nullable = false)) })
	public UsuarioGuicheId getId() {
		return this.id;
	}

	public void setId(UsuarioGuicheId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "porto_idPorto", nullable = false)
	public Porto getPorto() {
		return this.porto;
	}

	public void setPorto(Porto porto) {
		this.porto = porto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_idUsuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nGuiche")
	public Integer getNguiche() {
		return this.nguiche;
	}

	public void setNguiche(Integer nguiche) {
		this.nguiche = nguiche;
	}

}
