package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "fluvialpass")
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String nomeUsuario;
	private String emailUsuario;
	private String senhaAdmin;
	private Set<UsuarioVendedorPassagem> usuarioVendedorPassagems = new HashSet<UsuarioVendedorPassagem>(0);
	private Set<Login> logins = new HashSet<Login>(0);
	private Set<UsuarioWeb> usuarioWebs = new HashSet<UsuarioWeb>(0);
	private Set<UsuarioGuiche> usuarioGuiches = new HashSet<UsuarioGuiche>(0);
	private Set<Telefone> telefones = new HashSet<Telefone>(0);
	private Set<Endereco> enderecos = new HashSet<Endereco>(0);
	private Set<UsuarioApp> usuarioApps = new HashSet<UsuarioApp>(0);

	public Usuario() {
	}
	
	public Usuario(Integer idUsuario, String nomeUsuario, String emailUsuario, String senhaAdmin) {
		this.idUsuario = idUsuario;
		this.nomeUsuario = nomeUsuario;
		this.emailUsuario = emailUsuario;
		this.senhaAdmin = senhaAdmin;
	}

	public Usuario(Integer idUsuario, String nomeUsuario, String emailUsuario, String senhaAdmin,
			Set<UsuarioVendedorPassagem> usuarioVendedorPassagems, Set<Login> logins, Set<UsuarioWeb> usuarioWebs,
			Set<UsuarioGuiche> usuarioGuiches, Set<Telefone> telefones, Set<Endereco> enderecos,
			Set<UsuarioApp> usuarioApps) {
		this.idUsuario = idUsuario;
		this.nomeUsuario = nomeUsuario;
		this.emailUsuario = emailUsuario;
		this.senhaAdmin = senhaAdmin;
		this.usuarioVendedorPassagems = usuarioVendedorPassagems;
		this.logins = logins;
		this.usuarioWebs = usuarioWebs;
		this.usuarioGuiches = usuarioGuiches;
		this.telefones = telefones;
		this.enderecos = enderecos;
		this.usuarioApps = usuarioApps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUsuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "nomeUsuario", length = 45, unique = true, nullable = false)
	public String getNomeUsuario() {
		return this.nomeUsuario;
	}

	public void setNomeUsuario(String nomeUsuario) {
		this.nomeUsuario = nomeUsuario;
	}

	@Column(name = "emailUsuario", length = 256)
	public String getEmailUsuario() {
		return this.emailUsuario;
	}

	public void setEmailUsuario(String emailUsuario) {
		this.emailUsuario = emailUsuario;
	}
	
	@Column(name = "senhaAdmin", length = 10)
	public String getSenhaAdmin() {
		return senhaAdmin;
	}

	public void setSenhaAdmin(String senhaAdmin) {
		this.senhaAdmin = senhaAdmin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioVendedorPassagem> getUsuarioVendedorPassagems() {
		return this.usuarioVendedorPassagems;
	}

	public void setUsuarioVendedorPassagems(Set<UsuarioVendedorPassagem> usuarioVendedorPassagems) {
		this.usuarioVendedorPassagems = usuarioVendedorPassagems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Login> getLogins() {
		return this.logins;
	}

	public void setLogins(Set<Login> logins) {
		this.logins = logins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioWeb> getUsuarioWebs() {
		return this.usuarioWebs;
	}

	public void setUsuarioWebs(Set<UsuarioWeb> usuarioWebs) {
		this.usuarioWebs = usuarioWebs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioGuiche> getUsuarioGuiches() {
		return this.usuarioGuiches;
	}

	public void setUsuarioGuiches(Set<UsuarioGuiche> usuarioGuiches) {
		this.usuarioGuiches = usuarioGuiches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Telefone> getTelefones() {
		return this.telefones;
	}

	public void setTelefones(Set<Telefone> telefones) {
		this.telefones = telefones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioApp> getUsuarioApps() {
		return this.usuarioApps;
	}

	public void setUsuarioApps(Set<UsuarioApp> usuarioApps) {
		this.usuarioApps = usuarioApps;
	}

}
