package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsuarioVendedorPassagem generated by hbm2java
 */
@Entity
@Table(name = "usuario_vendedor_passagem", catalog = "fluvialpass")
public class UsuarioVendedorPassagem implements java.io.Serializable {

	private UsuarioVendedorPassagemId id;
	private Barco barco;
	private Usuario usuario;
	private String pontoVendaVendedor;
	private String cpf;
	private String rg;
	private Set<Passagem> passagems = new HashSet<Passagem>(0);

	public UsuarioVendedorPassagem() {
	}

	public UsuarioVendedorPassagem(UsuarioVendedorPassagemId id, Barco barco, Usuario usuario) {
		this.id = id;
		this.barco = barco;
		this.usuario = usuario;
	}

	public UsuarioVendedorPassagem(UsuarioVendedorPassagemId id, Barco barco, Usuario usuario,
			String pontoVendaVendedor, String cpf, String rg, Set<Passagem> passagems) {
		this.id = id;
		this.barco = barco;
		this.usuario = usuario;
		this.pontoVendaVendedor = pontoVendaVendedor;
		this.cpf = cpf;
		this.rg = rg;
		this.passagems = passagems;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idusuarioVendedorPassagem", column = @Column(name = "idusuario_vendedor_passagem", nullable = false)),
			@AttributeOverride(name = "usuarioIdUsuario", column = @Column(name = "usuario_idUsuario", nullable = false)) })
	public UsuarioVendedorPassagemId getId() {
		return this.id;
	}

	public void setId(UsuarioVendedorPassagemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idBarcoRepresenta", nullable = false)
	public Barco getBarco() {
		return this.barco;
	}

	public void setBarco(Barco barco) {
		this.barco = barco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_idUsuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "pontoVendaVendedor", length = 256)
	public String getPontoVendaVendedor() {
		return this.pontoVendaVendedor;
	}

	public void setPontoVendaVendedor(String pontoVendaVendedor) {
		this.pontoVendaVendedor = pontoVendaVendedor;
	}

	@Column(name = "cpf", length = 45)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "rg", length = 45)
	public String getRg() {
		return this.rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioVendedorPassagem")
	public Set<Passagem> getPassagems() {
		return this.passagems;
	}

	public void setPassagems(Set<Passagem> passagems) {
		this.passagems = passagems;
	}

}
