package br.com.ikaros.model;
// Generated Sep 5, 2017 1:14:19 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioWebId generated by hbm2java
 */
@Embeddable
public class UsuarioWebId implements java.io.Serializable {

	private int idusuarioWeb;
	private int usuarioIdUsuario;

	public UsuarioWebId() {
	}

	public UsuarioWebId(int idusuarioWeb, int usuarioIdUsuario) {
		this.idusuarioWeb = idusuarioWeb;
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "idusuario_web", nullable = false)
	public int getIdusuarioWeb() {
		return this.idusuarioWeb;
	}

	public void setIdusuarioWeb(int idusuarioWeb) {
		this.idusuarioWeb = idusuarioWeb;
	}

	@Column(name = "usuario_idUsuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioWebId))
			return false;
		UsuarioWebId castOther = (UsuarioWebId) other;

		return (this.getIdusuarioWeb() == castOther.getIdusuarioWeb())
				&& (this.getUsuarioIdUsuario() == castOther.getUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdusuarioWeb();
		result = 37 * result + this.getUsuarioIdUsuario();
		return result;
	}

}
